// K-designs catalogue. Source of every number: the design's own page on ikarus342000.org (link in `page`).
// Prices follow the shop page's price table (https://ikarus342000.org/Order.html) where it lists the design.
// `pages` = further source pages merged into the design. Photos: [file in img/<id>/ without .webp, caption]. The first photo is the card and hero picture.
// hours = the designer's own construction-time figure; null where he gives none.
// hoursEst = our estimate from comparable designs where he gives none (estBasis says how), shown with ≈.
window.KD = {
  email: "bernd@ikarus342000.com",
  group: "https://www.facebook.com/groups/726275624227305",
  cats: {
    small: "Beach & small boats",
    trailer: "Trailer cruisers",
    offshore: "Offshore cruisers",
    power: "Power & houseboats",
    experimental: "Experimental craft",
  },
  designs: [
    {
      id: "duo-425", name: "DUO 425", cat: "small", rig: "sail", year: null,
      tagline: "The fastest cat for your money",
      loa: 4.25, beam: 2.1, weight: 44, hours: 120, plan: 70, study: null, sleeps: "day boat",
      spec: [["Length", "4.25 m"], ["Beam", "2.10 m"], ["Weight of one hull", "17 kg"], ["Weight, ready to sail", "44 kg"], ["Sail area", "up to 16 m²"], ["Rig", "2 windsurf rigs, parallel"]],
      text: [
        "The DUO 425 was the first parallel-rig catamaran designed for amateur builders. The prototype was shown at the Düsseldorf boat show in 1984, and well over a thousand have been built since.",
        "Each asymmetric hull is made from only 16 main parts and is built flat on a table or the floor. Screws in pre-drilled holes line the parts up, a method borrowed from aluminium aircraft construction. Doctors, mechanics and office workers with no experience have built one in about 120 hours.",
        "The material list is short: four sheets of 4 mm plywood, one of 8 mm, 16 m of 20 × 20 mm strips, about 5 kg of epoxy and two windsurf rigs. The boat weighs 44 kg, goes on a car roof and is rigged in about 20 minutes. A second-hand DUO 425 was clocked at 34 knots near IJmuiden.",
      ],
      delivery: ["Plans with the right to build one boat"],
      photos: [["DUO425pepijnnet", "DUO 425 under its two windsurf rigs"], ["DUO425beachweb", "Flying a hull"], ["DUO425wall2001", "Rigged on the lawn, ready for the water"], ["Allpartsforahull_SC435_DUO425", "Every part of one hull"], ["AlignmDUO480C_03", "Matched-hole assembly: the hull lines itself up"], ["DUO425_Vieste_small", "On the beach"]],
      videos: [["How an asymmetric hull goes together", "https://www.youtube.com/watch?v=Qh5WMjMy5a4"]],
      page: "https://ikarus342000.org/DUO425pageX.html",
      pages: ["https://ikarus342000.org/KD860Bpage.html"],
    },
    {
      id: "sc-435", name: "SC 435", cat: "small", rig: "sail", year: 1979,
      tagline: "Bernd's first catamaran design, still sailing everywhere",
      loa: 4.35, beam: 2.1, weight: 66, hours: 120, plan: 70, study: null, sleeps: "day boat",
      spec: [["Length", "4.35 m"], ["Beam", "2.10 m"], ["Weight", "66 kg"], ["Sail area", "13 m²"], ["Parts per hull", "10"], ["Beams and mast", "standard aluminium tube"]],
      text: [
        "The SC 435 was Bernd Kohler's first catamaran, drawn in 1979. He has lost count of the plans sold; the boats sail in almost every country with water, and the latest one was built in Iceland.",
        "The asymmetric hulls line themselves up with the matched-hole method, so no jig is needed. One hull has only ten parts. Beams and mast are standard aluminium tubes, which saves time and money, and the boat is light enough for a roof rack. Some customers built theirs in four weeks of spare time.",
        "Fast and seaworthy: the first photo shows an SC 435 in wind force 7 to 8 off Terschelling in the Netherlands.",
      ],
      delivery: ["E-book with step-by-step building instructions, 18 pages", "22 drawings plus the new rig"],
      photos: [["SC435_windf7_h400_01", "Wind force 7 to 8 off Terschelling"], ["SC435isl_01", "The blue SC 435 built in Iceland"], ["SC435fi3_01", "Reaching"], ["SC435rug2", "Yellow sail, calm water"], ["SC435_croa", "Sailing in Croatia"], ["SC435_all_partparts_380", "All parts cut and ready"], ["Sc435_Bulk_mo_380", "Bulkheads in place"], ["SC435almready", "Almost ready"], ["SC435-redy-close", "Hull finished"]],
      videos: [["Sailing in Croatia", "https://www.youtube.com/watch?v=Y6UreNRCABo"], ["SC 435 slideshow", "https://www.youtube.com/watch?v=YJ2YmyJ6gog"], ["Asymmetric hull construction", "https://www.youtube.com/watch?v=Qh5WMjMy5a4"]],
      page: "https://www.ikarus342000.org/SC435page.html",
    },
    {
      id: "tiny-tri", name: "Tiny Tri", cat: "small", rig: "sail", year: null,
      tagline: "The smallest trimaran in the portfolio, built on stringers in a few steps",
      loa: 4.0, beam: 2.4, weight: 65, hours: null, hoursEst: 120, estBasis: "Bernd gives no figure. DUO 425 (44 kg) and SC 435 (66 kg) take about 120 hours; Tiny Tri weighs 65 kg and its hull is built on stringers, without stitch-and-glue.", plan: 70, study: null, sleeps: "day boat",
      spec: [["Length", "4.00 m"], ["Beam", "2.40 m"], ["Total weight", "65 kg"], ["Sail area", "9 m²"], ["Hull", "sharpie, built on stringers"], ["Mast", "rotating, with stays"]],
      text: [
        "Probably the easiest trimaran to build on the market, and easy on the bank account too. The main hull is a sharpie shape built on stringers, which takes fewer steps than stitch-and-glue.",
        "The floats work like water skis with some volume: they give static stability at rest and dynamic lift at speed, like foils without the fuss. The rotating mast keeps its stays thanks to a small top-mast rotator.",
        "The whole boat weighs 65 kg, so it can travel on a car roof in most countries. Its rig also sails on Matt's trimaran, an Alaska trail contender.",
      ],
      delivery: ["Building manual with photos", "Drawing set"],
      photos: [["Photovideo_01", "Tiny Tri under sail"], ["TTusblank_01", "Blue sail, white hull"], ["Rigmattsboat_01", "The Tiny Tri rig on Matt's trimaran"], ["TiniTri2_01", "Assembled on the grass"], ["Hullturned_01", "Main hull turned over"], ["Dagruclosed_01", "Hollow daggerboard and rudder"], ["Matchedholetech_01", "Matched-hole technique"], ["Topmastrotator_01", "Top-mast rotator: stays and a rotating mast"], ["Topmastbearing_01", "Top-mast bearing"]],
      videos: [],
      page: "https://ikarus342000.org/Tinytripage2.html",
    },
    {
      id: "little-tri", name: "Little Tri", cat: "small", rig: "sail", year: null,
      tagline: "A modern double-outrigger you can camp on",
      loa: 4.7, beam: 3.8, weight: 75, hours: 120, plan: 100, study: null, sleeps: "2 in a tent",
      spec: [["Length", "4.70 m"], ["Beam", "3.80 m"], ["Weight", "75 kg"], ["Sail area", "13 m²"], ["Buoyancy, hull only", "275 litres"], ["Rig", "Sunfish rig"], ["Build cost", "about US $1,500"]],
      text: [
        "Inspired by the Pacific outrigger canoes that settled the islands. The main hull is a plywood, glass and epoxy sharpie, the simplest shape to build, and the floats are PVC irrigation pipe instead of bamboo.",
        "If you can use a saw and a brush you can build it, for around US $1,500 with a low-cost Sunfish rig. It sets up quickly, the cockpit drains itself, and an igloo tent for two fits over the cockpit and trampoline for trekking.",
        "The hull alone floats 275 litres, so the boat is unsinkable. It is fast, easy for beginners, and has proved itself on coastal trips in wind and waves.",
      ],
      delivery: ["2 PDF brochures with step-by-step instructions, 22 pages and 23 photos", "20 drawings"],
      photos: [["Litr0_fast_01", "Little Tri at speed"], ["littletriam_250", "From above"], ["Littlejunk_250", "With a junk rig"], ["Litriikke_250", "At the helm"], ["little_tri-con_250", "In the workshop"], ["Listmat1_1", "List of materials"]],
      videos: [["Construction time-lapse", "https://www.youtube.com/watch?v=bP4wwV9XPOo"], ["Introduction", "https://www.youtube.com/watch?v=aVADN11Xbbk"], ["First sail", "https://www.youtube.com/watch?v=ENi2rWtJqu8"], ["Fun sailing", "https://www.youtube.com/watch?v=cANXDLV2tJM"]],
      page: "https://www.ikarus342000.org/LITTLETRIPAGE.html",
      pages: ["https://ikarus342000.org/LiTrimal.html"],
    },
    {
      id: "cataproa", name: "CATAPROA", cat: "small", rig: "sail", year: null,
      tagline: "A one-person cabin cruiser that tacks like a dinghy",
      loa: null, beam: 1.6, weight: 90, hours: 200, plan: 100, study: null, sleeps: "1",
      spec: [["Total weight", "90 kg"], ["Cabin", "2.0 × 0.9 m, 1 m sitting height"], ["Road width", "1.6 m"], ["Sail", "Sunfish lateen sail"], ["Set-up", "8 bolts and a windsurf mast"], ["Build cost", "about US $1,000"]],
      text: [
        "A new type of craft between a Pacific proa and a catamaran: it tacks like a catamaran instead of shunting, and manoeuvres like a dinghy. Possibly the easiest single-handed cabin multihull on the market, for coastal sailing and river or canal trekking.",
        "The cabin is 2 m long and 0.9 m wide. The boat weighs 90 kg, so beaching and launching are a one-person job, and the rudder kicks up by itself. On the road it is only 1.6 m wide; to sail, fasten eight bolts, step the windsurf mast and set the sail.",
        "It can be built ready to go for about US $1,000. Anybody who can repair a chair can build it.",
      ],
      delivery: ["Picture-story manual, 28 pages and 22 photos", "24 drawings as PDF"],
      photos: [["Catapsail_01", "Under its lateen sail"], ["Sailalicate_01", "In Alicante"], ["Cataproaachternharaldsmall_01", "Under construction"], ["ikkeins_01", "Room inside the cabin"], ["Cablayoutsmall_01", "Layout"], ["Cataproasailing_03", "Under sail"], ["Cataproadanmark_01", "Sailing in Denmark"], ["Cataproaroundt_01", "Ashore on a round trip"], ["Cataproabouw_01", "Building the hulls"]],
      layout: "Cablayoutsmall_01",
      videos: [["Construction", "https://www.youtube.com/watch?v=1ju39sXLTa4"], ["Sailing in Denmark", "https://www.youtube.com/watch?v=2nGChrDX3tg"], ["Inside the cabin", "https://www.youtube.com/watch?v=8-zk3MA9xK4"], ["Sailing near Alicante", "https://www.youtube.com/watch?v=ca_tT-dp1-0"], ["Another CATAPROA video", "https://www.youtube.com/watch?v=L7lHfEG81gM"]],
      page: "https://www.ikarus342000.org/CATAPROApage.html",
      pages: ["https://ikarus342000.org/DESIGNS.html"],
    },
    {
      id: "duo-480-a", name: "DUO 480 A", cat: "small", rig: "sail", year: null,
      tagline: "The open DUO 480 for rivers and coastal trekking",
      loa: 4.8, beam: 2.4, weight: 120, hours: null, hoursEst: 220, estBasis: "Bernd gives no figure. The DUO 480 C with its cabin takes about 300 hours, and this is the same boat without the cabin.", plan: 120, study: null, sleeps: "2 in a tent",
      spec: [["Length", "4.80 m"], ["Beam", "2.40 m, trailer as it is"], ["Weight", "120 kg"], ["Rig", "windsurf rigs"]],
      text: [
        "The DUO 480 without the cabin. The cockpit is roomy and an igloo tent fits on it for overnight trips on rivers and along the coast.",
        "At 2.4 m wide it trails as it is, and at 120 kg a small car can tow it. Material costs are low, and with second-hand windsurf rigs the whole boat stays cheap. The result is a fast, fun boat.",
        "Building needs nothing more than a flat surface.",
      ],
      delivery: ["Plans with the right to build one boat"],
      photos: [["DUO480Ccroatien2_01", "Sailing in Croatia"], ["Iglosmall2_01", "Igloo tent over the cockpit"], ["Perspecwindsrig", "With windsurf rigs"], ["Jigsawsideview488_01", "Side view"], ["Listmat_01", "List of materials"]],
      videos: [["How easy the hull is to build", "https://www.youtube.com/watch?v=Qh5WMjMy5a4"]],
      page: "https://ikarus342000.org/DUO480Adpage.html",
    },
    {
      id: "duo-480-c", name: "DUO 480 C", cat: "small", rig: "sail", year: null,
      tagline: "Micro cruiser with a biplane rig and a cabin for two",
      loa: 4.8, beam: 2.3, weight: 180, hours: 300, plan: 130, study: 10, sleeps: "2",
      spec: [["Length", "4.80 m"], ["Beam", "2.30 m"], ["Beam, hull centres", "2.06 m"], ["Empty weight", "180 kg"], ["Max. weight", "450 kg"], ["Sails", "2 × 8 m²"], ["Hull length : beam", "13.55 : 1"]],
      text: [
        "An easy-to-build micro cruiser for the weekend sailor. At 2.30 m wide it trails easily, and the windsurf masts and extensions are up in minutes.",
        "The biplane rig keeps the centre of pressure low, so the boat stands a lot of wind. Both sails roll around their masts and are furled from the cockpit. The asymmetric hulls need no boards or keels to go to windward, and the single rudder kicks up if you hit something. The cabin sleeps two.",
        "The asymmetric hulls align themselves on a flat surface, so no building frame is needed. An average amateur builds the boat in about 300 hours, and gudgeons, sail rollers, booms and the boom rotator can be home-made to save money.",
      ],
      delivery: ["33 DXF drawings", "Building description", "Study plan: 18 pages with bill of materials"],
      photos: [["DUO480CsailingNZ_small", "Sailing in New Zealand"], ["DUO480croatia_small", "Croatia"], ["Jigsawcroatiatopbig", "From the masthead"], ["DUO480croatien", "At the jetty"], ["DUO480_ins320jpeg", "Inside the cabin"], ["DUO480confront320", "Hulls and deck under construction"], ["from_back_glassed_and_faired", "Glassed and faired"], ["DUO480C_layout_01", "Layout"], ["DUO480cab10", "In New Zealand"], ["DUO480CNZ2_03", "Sailing in New Zealand"], ["DUO480Cman", "Under sail"], ["Brianjigsawportblog", "At the dock, from the New Zealand build blog"], ["Hulldeckgirsmall", "Hull and deck girders"], ["DUO480C_01", "Rendering with the biplane rig"]],
      layout: "DUO480C_layout_01",
      videos: [["Sailing in New Zealand, summer 2016/17", "https://www.youtube.com/watch?v=E-AyBsR-kt4"], ["Sailing and coming about", "https://www.youtube.com/watch?v=PiTbOKIuxlY"], ["More sailing", "https://www.youtube.com/watch?v=RKNuKw_z5hw"], ["Builder's blog, New Zealand", "https://duo480.blogspot.com/"]],
      page: "https://ikarus342000.org/DUO480Cpage.html",
      pages: ["https://ikarus342000.org/DESIGNS.html", "https://ikarus342000.org/Biplanrig.html", "https://ikarus342000.org/KD860Bpage.html"],
    },
    {
      id: "eco-520", name: "ECO 520", cat: "trailer", rig: "sail", year: null,
      tagline: "Affordable sailing again: asymmetric hulls, a home-made mast and no boards",
      loa: 5.2, beam: 2.5, weight: 280, hours: 500, plan: 140, study: 12, sleeps: "2",
      spec: [["Length", "5.20 m"], ["Beam", "2.50 m"], ["Draught, hull / rudder", "0.26 / 0.60 m"], ["Empty weight", "280 kg"], ["Max. weight", "580 kg"], ["Sail area, jib rig", "24 m²"], ["Hull length : beam", "14 : 1"], ["Outboard", "3 hp"]],
      text: [
        "Designed to make sailing affordable for everyone again: a coastal cruiser that trails behind a small car and sails easily under its jib rig. Two can sleep aboard on the double berth, with a folding table and a pantry.",
        "The asymmetric hulls need no keels or daggerboards, so you can reach very shallow water or beach the boat without risk. They are built flat on a floor or bench, which takes much less time than symmetric hulls, and the rudder kicks up by itself.",
        "The jib rig is not the most powerful for its area, but it is the most cost-efficient: the 7 m mast is built from 12 mm plywood and fir for around $80, and the boat otherwise sails like a sloop. Construction takes about 500 hours.",
      ],
      delivery: ["21 DXF drawings at 1:1", "Construction manual, 20 pages", "Study plan, 12 pages with list of materials, list of drawings and an example drawing"],
      photos: [["ECO520ren_web", "ECO 520 with its jib rig"], ["Layout1use", "Layout"], ["Entranceweb", "Drawing: entrance"], ["Mastsection_small", "Mast section: plywood and fir, 7 m long"], ["ECOPOWErins", "Interior of an ECO, shown on the ECO 520 page"], ["Orcaweb", "A jib rig on another boat"], ["PDracer_400", "A jib rig on a PD racer"]],
      layout: "Layout1use",
      videos: [],
      page: "https://ikarus342000.org/ECO520page.html",
    },
    {
      id: "eco-550", name: "ECO 550", cat: "trailer", rig: "sail", year: 2003, first: true,
      tagline: "The designer's pick for a first boat-building project",
      loa: 5.5, beam: 2.5, weight: 289, hours: 400, plan: 145, study: 12, sleeps: "3–4",
      spec: [["Length", "5.50 m"], ["Beam", "2.50 m"], ["Draught, hull / board", "0.22 / 1.00 m"], ["Weight", "289 kg"], ["Max. weight", "620 kg"], ["Mainsail", "11.4 m²"], ["Jib", "7.1 m²"]],
      text: [
        "The ECOnomy cruiser, first drawn in 2003, was the first multihull with a negative bow. Experience from builders around the world has gone into this updated version; the original rounded bow is still available if you prefer it.",
        "In the designer's words it is the perfect first boat-building project, and in capable hands a proven coastal cruiser. At 290 kg empty it goes behind a medium-sized car on a small trailer, straight from the trailer into the water. The single-chine hulls are simple and each cabin side is one sheet of plywood.",
        "Two rigs are drawn: a normal sloop, or a gunter rig with a single halyard and a 4.3 m mast you can make yourself from an 80 mm tube and an old windsurf mast. The rudders fold back when they hit something, and one daggerboard is handled from the cockpit. It sleeps three or four and has a good pantry. The quickest build so far took 400 hours.",
      ],
      delivery: ["31 CAD drawings as JPG or DXF", "Manual, 22 pages", "Study plan, 15 pages, includes the bill of materials", "Say which bow you want when you order: negative or the original rounded one"],
      materials: ["Plywood, okoume or fir, 2.44 × 1.22 m: 19 sheets of 6 mm, 3 of 12 mm, 1 of 8 mm, 4 of 4 mm and 2 of 4 mm birch",
        "Clear fir: about 90 m of 20 × 25 mm stringers, 50 m of 25 × 35 mm, plus stem and keel; spruce for rudders and board",
        "Epoxy and hardener 40 kg, silica 3 kg, microspheres 4 kg",
        "Glass cloth 240 g/m², 50 m²; unidirectional carbon tape for the rudders and daggerboard",
        "Aluminium tube 70/66 mm × 6.4 m for the mast; outboard up to 6 hp"],
      photos: [["ECO55dail_web", "ECO 550 under sail"], ["ECO55_action_web", "Gunter rig in action"], ["Sailinglookforward_Nic", "Looking forward, Nicaragua"], ["ECO55_jetty_Nic_web", "The Nicaragua build at the jetty"], ["ECO55_Aust_ready_web", "The Australian build, ready to launch"], ["ECO55_Nic_web", "Nicaragua: leeboards and a home-made rig"], ["ECO55_hulls_nic_web", "Hulls taking shape"], ["ECO55_instring_web", "Stringers in"], ["ECO_hull_NZ_CON_web", "Hull built in New Zealand"], ["ECObunksm_01", "The bunk"], ["ECOgunterrigsmalll", "Gunter rig drawing"], ["ecotop_04_01", "Top view"], ["Entrweb1", "Sample drawing, reduced from 1:10"], ["Gurigtop_web", "Gunter rig: the mast top"], ["KD650gunterigmasttop_web", "Gunter mast top on a KD 650"], ["J-class_gunterrig_web", "A classic gunter rig"]],
      videos: [["Construction and more", "https://www.youtube.com/watch?v=ioKESt3xtUU"], ["A nice afternoon sail", "https://www.youtube.com/watch?v=so5nJ9gckJ4"], ["A fast sail", "https://www.youtube.com/watch?v=cRvzFJURTVY"]],
      page: "https://ikarus342000.org/ECOpage.html",
      pages: ["https://ikarus342000.org/ECO5page2.html"],
    },
    {
      id: "eco-550-power", name: "ECO 550 Power", cat: "power", rig: "power", year: null,
      tagline: "The ECO trailer cat with an outboard, sailed as far as Alaska",
      loa: 5.5, beam: 2.5, weight: null, hours: 400, plan: 145, study: 12, sleeps: "3–4",
      spec: [["Length", "5.50 m"], ["Beam", "2.50 m"], ["Propulsion", "outboard"], ["Construction", "wood / epoxy composite"]],
      text: [
        "The power version of the ECOnomy cruiser. Boats have been built from the UK and Russia to the Americas, and one has cruised to Alaska.",
        "Like the sail version it is a true trailer boat, from the trailer into the water with no set-up time. The single-chine hulls are easy to build and each cabin side is one sheet of plywood. The original rounded bow is still available; say which version you want when you order.",
        "The K-designs builders' group has more than 850 members and over 2,000 photos of boats at every stage of construction.",
      ],
      delivery: ["31 CAD drawings as JPG or DXF", "Manual, 22 pages", "Study plan with the bill of materials", "Say which bow you want when you order: negative or the original rounded one"],
      photos: [["ECOaftnew2_01", "ECO 550 Power at the dock"], ["image0", "Under way"], ["ECOalaska2", "On an Alaskan beach"], ["ECO55elec2", "In the marina"], ["ECO55_Fun", "Out for the day"], ["ECO55berth", "The berth"], ["ECOinsidesmall", "Headroom inside"], ["ECOmuellerinsidevsmall_01", "Interior"], ["ecotop_04_01_01", "Top view"], ["ECO55_Miss", "At the dock"]],
      videos: [["Construction video", "https://www.youtube.com/watch?v=a2uiNIc1YMI"]],
      page: "https://ikarus342000.org/ECO55powerpage.html",
    },
    {
      id: "eco-6", name: "ECO 6", cat: "trailer", rig: "sail", year: null,
      tagline: "Half a metre longer than the ECO 550, with an enclosed toilet room",
      loa: 6.0, beam: 2.84, weight: 360, hours: 800, plan: 180, study: 12, sleeps: "3",
      spec: [["Length", "6.00 m"], ["Beam", "2.84 m"], ["Draught, hull / board", "0.22 / 1.00 m"], ["Empty weight", "360 kg"], ["Max. weight", "750 kg"], ["Mainsail", "15 m²"], ["Jib", "5.8 or 4.8 m², depending on the rig"], ["Code 1, extra", "16 m²"], ["Outboard", "up to 6 hp"], ["Headroom in the hulls", "1.64 m"]],
      text: [
        "The next size up in the ECOnomy series. Only half a metre longer than the ECO 550 but wider, which gives more than 20% more room: an enclosed toilet compartment, much more stowage, and a double bunk that converts to seating for four.",
        "The plans show a sloop rig and a single-halyard gunter rig. Bernd's choice is the gunter: as efficient as a fat-head rig at a fraction of the cost, with a plain aluminium tube as the mast and a short spar for trailering. Transom steps sit between the asymmetrically mounted kick-up rudders.",
        "Good material for the whole boat cost about €4,000 in the Netherlands; with rig, a 6 hp outboard and fittings, a careful builder gets the boat on the water for about US $8,000.",
      ],
      delivery: ["31 drawings", "Manual, 26 pages with construction photos", "Study plan with speed prediction, stability diagram and bill of materials"],
      photos: [["ECO6_David_sailing_01", "David's ECO 6 under gunter rig"], ["ECO6NZtitel_800_02", "Sailing in New Zealand"], ["ECO6topshortgaff_small_01", "The short gaff"], ["ECO6_cocy_01", "Cosy reading corner"], ["ECO6interior_01", "Part of the cabin"], ["ECO6_pantry_NZ_01", "Pantry"], ["ECO6_toilet_03", "The separate toilet room"], ["ECO6transom_ru_01", "Transom steps and kick-up rudder"], ["ECO6rot_01", "Ready for launching"], ["ECO6partpl_NZ_01", "Partly planked"], ["ECO6forwcon_CA_01", "Forward section under construction"], ["Layout2017_02", "Layout"]],
      layout: "Layout2017_02",
      videos: [["David's build video", "https://www.youtube.com/watch?v=oNo16UO28ZA"]],
      page: "https://ikarus342000.org/ECO6page3.html",
    },
    {
      id: "eco-6-p", name: "ECO 6 P", cat: "power", rig: "power", year: null, soon: true,
      tagline: "A 6.4 m power cat, 28 knots on paper with 34 hp",
      loa: 6.4, beam: 2.84, weight: 410, hours: 800, plan: null, study: null, sleeps: "",
      spec: [["Length", "6.40 m"], ["Beam", "2.84 m"], ["Draught", "0.22 m"], ["Empty weight", "410 kg"], ["Max. weight", "820 kg"], ["Engine for calculation", "34 hp"], ["Calculated top speed", "28 kn at 800 kg"]],
      text: [
        "The power version of the ECO 6 is on the drawing board. Preliminary figures: 6.4 m long, 410 kg empty, and a calculated 28 knots at full power with a 34 hp engine and 800 kg on board.",
        "The hulls are 70% the same as the ECO 6 sail version and go together in the same sequence. Without the mast support the saloon gains a lot of space. The seat backrest lies flat under the mattress at night, an idea first used on the P 95, and the entrance gets a sliding door.",
        "Construction is the same plywood, glass and epoxy composite, about 800 hours. Write to Bernd to be told when the plans are ready.",
      ],
      delivery: ["Coming soon"],
      photos: [["ECO6PdefAugust_web", "ECO 6 P, preliminary drawing"], ["Rendering", "Saloon rendering"], ["ECO6sal_collage_web", "Seating by day, berth by night"], ["Layout_800", "Layout"], ["Bulkheads_setup_small", "Bulkheads set up, ECO 6 sail"], ["Bow_perspective_small", "Bow sections"], ["planking_small", "Planking"], ["Hulls_turned_200", "Hulls turned"], ["Bridge_deck_floor_small", "Bridge-deck floor"], ["ECO6partsaloon_CA_small", "Part of the saloon, ECO 6 sail"]],
      layout: "Layout_800",
      videos: [],
      page: "https://ikarus342000.org/ECO6Ppage.html",
      pages: ["https://ikarus342000.org/ECO6power2.html"],
    },
    {
      id: "eco-62-h", name: "ECO 62 H", cat: "power", rig: "power", year: null,
      tagline: "A light houseboat with standing headroom and a 12 m² solar roof",
      loa: 6.2, beam: 2.5, weight: 410, hours: 800, plan: 240, study: 12, sleeps: "2",
      spec: [["Length", "6.20 m"], ["Beam", "2.50 m"], ["Draught", "0.23 m"], ["Empty weight", "410 kg"], ["Max. weight", "890 kg"], ["Headroom", "1.93 m"], ["Solar roof", "12 m², about 2.16 kW"], ["Buoyancy in the hulls", "1,400 litres"]],
      text: [
        "A catamaran houseboat that is lighter and more seaworthy than most houseboats of its size, and carries more than its own weight. The hulls slide through the water easily, so it needs little power.",
        "The roof can take 12 m² of solar panels, about 2.16 kW, enough for 8 km/h, the speed limit on many canals. Power can be small electric trolling motors (one at the bow, two at the transom), a 15 hp surface drive for about 12 knots, or a 20 hp outboard.",
        "Standing headroom is 1.93 m and the saloon is reached from the cockpit without steps. A double berth in the bow frees up living space, and the empty hulls leave room for water and waste tanks. It is built in three parts from mostly straight cuts; one hull weighs about 50 kg.",
      ],
      delivery: ["17 CAD/CAM drawings, partly usable for CNC cutting", "Instructions, 18 pages", "Study plan with the list of materials"],
      photos: [["ECO62marina", "ECO 62 H in the marina"], ["bussy_bord", "Afloat among the yachts"], ["ECO62_dinette_260", "Dinette"], ["ECO62_kitchen_260", "Kitchen"], ["ECO62_forw2_260", "Looking forward"], ["ECO62_Helm_260", "Helm position"], ["ECO62_bathrpart_260", "Bathroom"], ["ECO62Undersidepainted", "Underside painted"], ["ECO62_Ins_ren_300", "Interior rendering"], ["ECO62layout_1000", "Layout"]],
      layout: "ECO62layout_1000",
      videos: [["Construction", "https://www.youtube.com/watch?v=EUtYF_ArRt8"], ["First trial trip", "https://www.youtube.com/watch?v=hA4ZkgbASTQ"]],
      page: "https://ikarus342000.org/ECO62page2.html",
    },
    {
      id: "eco-75", name: "ECO 75", cat: "offshore", rig: "sail", year: 2004,
      tagline: "The big sister of the ECO 550, with electric drive as an option",
      loa: 7.5, beam: 4.5, weight: 750, hours: null, hoursEst: 1000, estBasis: "Bernd gives no figure. The DUO 800 S (830 kg) takes about 900 hours and the P 95 (1,050 kg) about 1,000; the ECO 75 weighs about 750 kg.", plan: 290, study: 12, sleeps: "",
      spec: [["Length", "7.50 m, 7.75 m with rudders"], ["Beam", "4.50 m"], ["Draught, without rudders / board down", "0.30 / 1.30 m"], ["Empty weight", "about 750 kg"], ["Max. weight", "1,384 kg"], ["Sail area", "28.6 m² sloop, 27.6 m² wishbone gaff"], ["Outboards", "about 2 × 5 hp"], ["Electric drive", "2 × 1.5 kW"], ["Headroom in the hulls", "1.82–1.92 m"]],
      text: [
        "Designed in 2004 and built in many countries since, from India and Karimun Jawa to New Zealand. One boat built in India sailed 2,600 miles along the whole Indian coast.",
        "The logical bigger version of the ECO 550, but a different boat: the hulls are multi-chine, with 1.82 to 1.92 m headroom where it counts, and there is a lot of storage inside and out for long holidays. Owners have used it for long-distance cruising as well as along the coast.",
        "Two sail plans are drawn: a conventional fractional rig, or a wishbone gaff rig with a roller-reefing jackstay for quick mainsail handling. The wishbone rig is more effective than a roller-reefed triangular sail and cheaper, because it is made from aluminium tube; its drawings are in the plans.",
        "Power is two outboards of about 5 hp, one centre-mounted outboard, or an electric drive of 2 × 1.5 kW. The daggerboard and rudders, built from 4 mm plywood with glass and carbon, jump up when they hit something. A jigsaw, a good sander and basic woodworking tools are all you need.",
      ],
      delivery: ["30 DXF drawings at 1:10 or 1:1, the important bulkheads at 1:1", "Building instructions, 24 pages, plus 4 picture pages on the difficult parts", "Separate plan for the wishbone rig", "Study plan with the list of materials"],
      photos: [["ECO75_achtern_web", "ECO 75 under sail"], ["ECO75_sail4_g", "Sailing with friends"], ["ECO75_port_super", "In the marina"], ["ECO75warftopindia_260", "Launching the boat built in India"], ["ECO75toilet_part_260", "Toilet compartment"], ["ECO75pantrygalley_260", "Pantry"], ["ECO7.5wishbone_260", "The mast"], ["ECO75afloat", "At anchor"], ["ECO7.5beach3", "Off the beach"], ["ECO75obob_web", "The deck from above"], ["Untitled", "Solar panels on the cabin roof"], ["Inside_1", "Inside the bridge deck"], ["Stbhull", "Starboard hull"], ["Wishboneupsmall", "Wishbone gaff rig"], ["ECO7front", "Under construction"], ["hullconstruction", "Hull construction"], ["wet_area", "Wet area in plywood"], ["ECO75_layout_720", "Layout"], ["more-moving", "At the pontoon"], ["Pantry3small", "Pantry"], ["pantrysmall", "Pantry in plywood"], ["Wishbonelowsmall", "Wishbone boom"], ["mastbeam", "Mast beam"], ["n_a", "Under construction"]],
      layout: "ECO75_layout_720",
      videos: [],
      page: "https://ikarus342000.org/ECO75Sailpage.html",
      pages: ["https://ikarus342000.org/ECO75page.html", "https://ikarus342000.org/ECO7page2.html"],
    },
    {
      id: "eco-75-p", name: "ECO 75 P", cat: "power", rig: "power", year: 2008,
      tagline: "The power cat with the front cockpit, built from Tahiti to Thailand",
      loa: 7.5, beam: 3.22, weight: 800, hours: null, hoursEst: 1000, estBasis: "Bernd gives no figure. The DUO 800 S (830 kg) takes about 900 hours and the P 95 (1,050 kg) about 1,000; the ECO 75 P weighs 800 kg and has a fitted bridge-deck saloon.", plan: 290, study: 12, sleeps: "4",
      spec: [["Length", "7.50 m"], ["Beam", "3.22 m"], ["Empty weight", "800 kg"], ["Max. weight", "1,400 kg"], ["Outboard", "20–40 hp"], ["Speed", "18–25 knots"], ["Hull planking", "8 mm plywood"]],
      text: [
        "A light, economical, low-maintenance power catamaran. Drawn in 2008, it was the first catamaran with a front cockpit. The medium-speed hulls are seaworthy, the hulls have standing headroom, and the bridge-deck saloon has comfortable seating. It reaches about 25 knots with 40 hp, or 18 knots at half power.",
        "It has been built in many countries and versions: a day-charter boat in Tahiti, solar-electric boats, and a luxurious one in Thailand. The interior can be arranged as you like as long as the bulkhead spacing stays unchanged.",
        "The V-hulls are built upside down on seven bulkheads with chine, sheer and two intermediate stringers, then planked with 8 mm plywood. Panels are epoxy-coated and sanded flat before they go on, which saves hundreds of hours later. Each hull is glassed and painted before it is turned.",
      ],
      delivery: ["DXF drawings to scale", "Construction manual as PDF", "The right to build one boat", "Study plan with the list of materials"],
      photos: [["ECO75tahiti_ancjhor_small", "At anchor in Tahiti"], ["ECO75electric_web", "The solar-electric ECO 75"], ["ECO75onwater", "On the water"], ["ECO8forwcockpit", "In the front cockpit"], ["ECO75_saloon_web", "Saloon"], ["ECO75_pantry_web2", "Pantry"], ["ECOP75_bathr2_web", "Bathroom"], ["ECO75Phustring_Ta", "Hull on its stringers"], ["ECO75_part_planked", "Partly planked"], ["ECO75bow", "Bow section"], ["ECO75_Ta_readyfortransport", "Ready for transport"], ["ECO75_t_readyforwatter", "Ready for the water"], ["ECO75Pstringbulk_web", "Bulkheads and stringers"], ["ECO75_layout_web", "Layout"], ["ECO8morea_04", "At anchor"]],
      layout: "ECO75_layout_web",
      videos: [["Pre-coating plywood panels, the quick way", "https://www.youtube.com/watch?v=V1GfJ-XHwf8"]],
      page: "https://www.ikarus342000.org/ECO75Ppage.html",
      pages: ["https://ikarus342000.org/DESIGNS.html"],
    },
    {
      id: "duo-800", name: "DUO 800", cat: "trailer", rig: "sail", year: 1980,
      tagline: "The only eight-metre cat with a central nacelle, sailed from Germany to Norway",
      loa: 8.0, beam: 4.25, weight: 550, hours: 800, plan: 290, study: 15, sleeps: "3–4",
      spec: [["Length", "8.00 m"], ["Beam", "4.25 m"], ["Draught, hull / rudder", "0.28 / 0.60 m"], ["Empty weight", "550 kg"], ["Max. weight", "922 kg"], ["Sail area", "28.6 m² sloop, 34.6 m² parallel rig"], ["Outboard", "5 hp"]],
      text: [
        "Drawn in 1980 as the next step after the DUO 425 and SC 435, and built in Australia, Germany, India, the Philippines and the UK. One owner sailed his from Germany to Norway.",
        "The central nacelle is surprisingly roomy: four for a weekend or three for a holiday. With a purpose-built trailer the boat is set up in about an hour. Choose a sloop rig, or the parallel biplane rig with carbon masts; the plans include the only DIY carbon-mast description on the market, no vacuum bagging needed.",
        "The asymmetric hulls are built on a floor or a table, with no lofting and no building frame, which makes it a sound first big project. The beams are standard aluminium tubes.",
      ],
      delivery: ["38 drawings as DXF, 1:10 or 1:1", "24 pages of building instructions", "4 picture pages on the difficult parts", "Study plan, 14 pages"],
      photos: [["DUO800sailf460_02", "Sailing"], ["DUO800water2_02", "Close-hauled"], ["DUO800_sluis", "Number 1 in a Dutch lock"], ["DUO800philip_02", "DUO 800 in the Philippines"], ["DUO800_Ondeck", "On deck"], ["DUO800cabinside", "Inside the nacelle"], ["DUO800_portbed", "Port berth"], ["Nacelle_pantry", "Nacelle pantry"], ["DUO800_hulls_Bredagne", "Hulls built on a table"], ["DUO800nacell-Con", "Nacelle under construction"], ["DUO800no1", "Hulls ready to paint"], ["DUO800india3_small", "Built in India, with the parallel rig"], ["duo-800india_01", "Another DUO 800 from India"]],
      videos: [["DUO 480 Jigsaw sailing: how asymmetric hulls come about", "https://www.youtube.com/watch?v=PiTbOKIuxlY"]],
      page: "https://ikarus342000.org/DUO800page.html",
      pages: ["https://ikarus342000.org/Biplanrig.html", "https://ikarus342000.org/KD860Bpage.html"],
    },
    {
      id: "duo-800-s", name: "DUO 800 S", cat: "trailer", rig: "sail", year: null,
      tagline: "The DUO 800 with symmetric hulls and room for a bathroom",
      loa: 8.25, beam: 5.02, weight: 830, hours: 900, plan: 390, study: 15, sleeps: "3",
      spec: [["Length", "8.25 m"], ["Beam", "5.02 m"], ["Draught, board up / down", "0.40 / 1.39 m"], ["Empty weight", "830 kg"], ["Max. weight", "1,500 kg"], ["Sail area, parallel rig", "34.6 m²"], ["Outboard", "10 hp"]],
      text: [
        "The big brother of the asymmetric DUO 800. It carries more and has less wetted surface, so it is quicker in light wind.",
        "The wider hulls take a bathroom in one hull and an extra berth in the other, and the sleek nacelle is easy to build. At 830 kg it can still be trailed behind a modest car. The original DUO 800 has made long passages; the S does the same in more comfort.",
      ],
      delivery: ["31 drawings, all DXF at 1:1", "Instructions, 29 pages", "Study plan, 13 pages with the list of materials"],
      photos: [["Perbluewater", "DUO 800 S"], ["Layoutillsmall", "Layout"], ["Bathroomweb", "Drawing: the port-side bathroom"]],
      layout: "Layoutillsmall",
      videos: [],
      page: "https://ikarus342000.org/DUO800Spage.html",
    },
    {
      id: "duo-900", name: "DUO 900", cat: "trailer", rig: "sail", year: null,
      tagline: "Trailerable coastal cat with 1.82 m headroom",
      loa: 8.99, beam: 4.52, weight: 700, hours: 900, plan: 290, study: 15, sleeps: "3",
      spec: [["Length", "8.99 m"], ["Beam", "4.52 m"], ["Draught", "0.43 / 0.70 m"], ["Empty weight", "700 kg"], ["Loaded weight", "1,776 kg"], ["Mainsail + jib", "30 + 10 m²"], ["Auxiliary", "12 hp"], ["Cabin headroom", "1.82 m"]],
      text: [
        "Drawn for a French client who wanted one catamaran for canals and the sea. European trailer width limits the hulls to 1.25 m, yet the layout sleeps three and cabin headroom is 1.82 m.",
        "The asymmetric hulls need no boards or keels. The boat is mostly 8 mm plywood on stringers, the simplest way to build; even beginners should need no more than 900 hours.",
      ],
      delivery: ["All drawings as CAD (DXF) files by e-mail", "Study plan, 13 pages with drawing list and list of materials"],
      photos: [["DUO900_redswim", "At anchor"], ["DUO900_sailing", "Under sail"], ["DUO900_anchor", "Anchored off the coast"], ["DUO900_inport", "In port"], ["DUO900_marina", "In the marina"], ["DUO900begin", "All the bulkheads"], ["DUO900_hullstringers_280", "Hull stringers"], ["DUO900_Hull_turn_280", "Turning a hull"], ["DUO900_readypaint_280", "Ready to paint"], ["DUO900Hull_cabready_280", "Hull and cabin ready"], ["LAYOUTabove_01", "Layout"]],
      layout: "LAYOUTabove_01",
      videos: [],
      page: "https://ikarus342000.org/DUO900page.html",
    },
    {
      id: "kd-860", name: "KD 860", cat: "offshore", rig: "sail", year: null,
      tagline: "Proven offshore cruiser with 0.4 m draught",
      loa: 8.6, beam: 5.6, weight: 1800, hours: 1200, plan: 400, study: 15, sleeps: "4",
      spec: [["Length", "8.60 m"], ["Beam", "5.60 m"], ["Draught, hull / board", "0.4 / 1.1 m"], ["Empty weight", "1,800 kg"], ["Loaded weight", "3,000 kg"], ["Main + jib + reacher", "27 + 10 + 26 m²"], ["Outboards", "2 × 6 hp"], ["Optimum speed", "21.5 kn"], ["Headroom, hulls / central cabin", "1.95 / 1.48 m"], ["Hull length : beam", "11 : 1"]],
      text: [
        "A proven offshore cruiser sailing all over the world; the plans now include many improvements and additions. The boat is light, with a low, streamlined profile for windward performance, and the study plan includes speed-prediction and stability diagrams.",
        "The trapezoid hulls are the same as the PELICAN's. For windward work choose anti-vortex panels, a single daggerboard in the port hull, or Bernd's favourite, a centre daggerboard under the bridge deck that kicks back if it hits something.",
        "Bernd used the experience of living aboard PELICAN so that a cat of this size would not become a floating caravan. Standing headroom, 1.95 m, is in the hulls; the central cabin is 1.48 m high with ample seating. Three entrances make moving about easy: port and starboard into the hulls, and one in the centre into the saloon. There is room for four on extended voyages.",
        "With 0.4 m draught it reaches coves other boats cannot, and it has crossed oceans. Many have been built, a lot of them in Brazil. Construction takes around 1,200 hours.",
      ],
      delivery: ["Building description, 34 pages", "55 DXF drawings and illustrations, including the daggerboards", "Study plan, 29 pages with 10 pictures, speed prediction and list of materials"],
      photos: [["KD860Sfi", "KD 860 under sail"], ["Cartasisawind", "Beating to windward"], ["KD860enterport2", "Entering port"], ["Portugalzenithtransomview", "In Portugal"], ["Icarsailingweb", "Solar panels on deck"], ["saloongm", "Central cabin"], ["Porthullentrancesm", "Port hull entrance"], ["Porthullberthssm", "Berths in the port hull"], ["Pantryfromssm", "Pantry"], ["KD860_do_ob_small", "The whole entrance opens up"], ["KD860_do_closed_web", "Entrance closed"], ["KD860con2", "Under construction"], ["KD860dwars_render", "Cross-section: headroom in the hulls"], ["Carsegelnspiachtern_03", "Downwind under spinnaker"], ["KD860thailandsmall_01", "Another KD 860 under sail"], ["KD860_brazil_web", "A KD 860 built in Brazil"], ["KDtasfrontsmall_02_01", "Bridge deck under construction"]],
      videos: [["KD 860 video", "https://www.youtube.com/watch?v=Bv-ath_xmjY"], ["Icarus video", "https://www.youtube.com/watch?v=PlROg6j4j_Y"], ["On the water", "https://www.youtube.com/watch?v=03_9lkJbcO4"], ["Walk-through", "https://www.youtube.com/watch?v=MTGvdaHI4VY"], ["KD 860s built in Brazil", "https://www.youtube.com/watch?v=CWfvynLKMdA"]],
      page: "https://ikarus342000.org/KD860page.html",
      pages: ["https://ikarus342000.org/DESIGNS.html", "https://ikarus342000.org/KD860page2.html"],
    },
    {
      id: "kd-860-open", name: "KD 860 Open", cat: "offshore", rig: "sail", year: null,
      tagline: "The open KD 860 with a parallel rig: 8 aboard for a day, 4 for cruising",
      loa: 8.2, beam: 3.8, weight: 910, hours: null, hoursEst: 1200, estBasis: "The Open page gives no figure; the related KD 860 B page, with the same biplane rig, gives about 1,200 hours.", plan: 400, study: 15, sleeps: "4",
      spec: [["Length", "8.20 m"], ["Beam", "3.80 m"], ["Draught", "0.31 m"], ["Weight", "910 kg"], ["Max. weight", "2,270 kg"], ["Power", "10–40 hp, electric or petrol outboard"]],
      text: [
        "The open version of the KD 860. Customers asked, so it carries the parallel (biplane) rig Bernd has used since 1984. The rig's lower centre of pressure and larger sail area make it faster than the original.",
        "Everything good about the KD 860 stays: the hull shape, the kick-up rudders and the anti-vortex panels. The low draught lets you anchor where other boats cannot.",
        "Easy to build, also for first-timers. Eight people can day-sail on it, four can cruise in comfort.",
        "A related page, KD 860 B, lists different figures (8.85 m long, 1,300 kg empty, 2,800 kg loaded, about 1,200 hours) and a 400-dollar plan set of 31 DXF drawings. Ask Bernd which version you are ordering.",
      ],
      delivery: ["Plans as PDF", "Study plan with 2 example drawings and the list of materials"],
      photos: [["KD860_ren2", "KD 860 Open, rendering"], ["Topillusright510_01", "Layout from above"], ["Insideportwebsmall_01", "Inboard profile"], ["KD860Bweb_01", "KD 860 B rendering"], ["KD860sidesmall_01", "KD 860 B side view"]],
      layout: "Topillusright510_01",
      videos: [],
      page: "https://ikarus342000.org/KD860openpage.html",
      pages: ["https://ikarus342000.org/KD860Bpage.html"],
    },
    {
      id: "p-95", name: "P 95", cat: "offshore", rig: "sail", year: null,
      tagline: "As fast as she looks: over 20 knots, no boards needed",
      loa: 9.5, beam: 5.2, weight: 1050, hours: 1000, plan: 320, study: 18, sleeps: "4",
      spec: [["Length", "9.50 m"], ["Beam", "5.20 m"], ["Draught, hulls / rudder", "0.43 / 0.65 m"], ["Empty weight", "1,050 kg"], ["Loaded weight", "1,750 kg"], ["Main + jib", "28 + 10.8 m²"], ["Genoa", "27 m²"], ["Outboard", "9.9 hp"]],
      text: [
        "Speeds over 20 knots come easily. The asymmetric hulls need no boards or keels to go to windward, and the boat does not yaw in a following sea.",
        "The main cabin on the beam is laid out for four people; the hulls hold two bunks, the pantry, the head and the chart table. Two big hatches ventilate well, and when closed the boat is watertight. A rotating wing mast is drawn, or use a regular mast.",
        "It can be built in parts (hulls, centre section, aft beam) and joined later. The 41 drawings cover details down to the short boom, chainplates and wiring. About 1,000 hours for an amateur.",
      ],
      delivery: ["41 drawings", "Study plan"],
      photos: [["P95frontweb", "P 95 at the dock"], ["P_95_speed_webpage", "At speed"], ["P95stbweb", "Starboard side"], ["P95backsidetommyweb", "Stern view"], ["P95cabinwebpage", "Main cabin"], ["P95cabinstbwebpage", "Starboard hull"], ["P95collage390", "Interior sketch"], ["Ruddersystem_1504274", "Rudder system"], ["P95LAYOUT", "Layout"], ["P95segelnbelt_03", "Sailing"]],
      layout: "P95LAYOUT",
      videos: [],
      page: "https://www.ikarus342000.org/P95page.html",
      pages: ["https://ikarus342000.org/DESIGNS.html"],
    },
    {
      id: "pelican", name: "PELICAN", cat: "offshore", rig: "sail", year: null,
      tagline: "The designer's own boat, his home for 11 years",
      loa: 10.5, beam: 6.85, weight: 2200, hours: null, hoursEst: 2000, estBasis: "Bernd gives no figure. The KD 1000 (2,000 kg) takes about 2,000 hours, and one builder finished his PELICAN in exactly a year.", plan: 999, study: 20, sleeps: "5",
      spec: [["Length", "10.50 m"], ["Beam", "6.85 m"], ["Draught", "0.64 m"], ["Empty weight", "2,200 kg"], ["Loaded weight", "4,200 kg"], ["Main + jib", "32 + 20 m²"], ["Reacher", "60 m²"], ["Auxiliary", "22 hp"]],
      text: [
        "An affordable offshore cruiser that any handy amateur can build. The designer chose it for his own use and lived aboard for 11 years, in good weather and bad; even in a winter mistral of force 9 to 10 the crew felt safe. Their average speed over all that sailing was 9.8 knots, with a top speed of 16.",
        "It points as high as a good monohull with only 0.64 m draught. Instead of daggerboards or keels it uses anti-vortex panels, a kind of winglet. All sails, the main included, are handled from the cockpit. Two double cabins and a single berth, plenty of stowage for long passages.",
        "The hulls are built on a flat backbone that fixes their shape once the bulkheads are slotted in, so both hulls come out the same. The drawings are honest hand-drawn plans. One builder finished his PELICAN in exactly a year.",
      ],
      delivery: ["38 original hand-drawn drawings plus building description, sent by air mail", "Study plan, 23 pages with pictures and list of materials"],
      photos: [["Pelica_water_small", "PELICAN at anchor"], ["Pelicanwebal2", "Under way"], ["Seatcorner", "Saloon corner"], ["Cockpitpe", "Cockpit"], ["BerthroomPe", "Double cabin"], ["Pelilayout", "Layout"], ["Pelican", "Lifting a hull"], ["Pelicanbau", "Under construction"], ["Peldraw1", "Drawing"]],
      layout: "Pelilayout",
      videos: [],
      page: "https://ikarus342000.org/Pelicanpage.html",
    },
    {
      id: "kd-1000", name: "KD 1000", cat: "offshore", rig: "sail", year: null,
      tagline: "Go-anywhere family cruiser with a 0.4 m loaded draught",
      loa: 10.0, beam: 6.22, weight: 2000, hours: 2000, plan: 1700, study: 20, studyRefund: true, sleeps: "4",
      spec: [["Length", "10.00 m, without rudders"], ["Beam", "6.22 m"], ["Draught, hulls / board", "0.39 / 1.70 m"], ["Empty weight", "2,000 kg"], ["Max. weight", "4,200 kg"], ["Main + jib", "30 + 13.5 m²"], ["Genoa", "40 m²"], ["Outboards", "2 × 10 hp"]],
      text: [
        "The result of a lot of research and of listening to customers. The multi-chine hulls with rounded sides take about 400 hours each; the geodetic coach roof of three layers of 4 mm plywood, bent over templates, saves about 70% of the usual time.",
        "The master cabin sits where the boat moves least, in a split-level layout with a view across the saloon. The galley is in the port hull, away from the saloon, and the bathroom is unusually large for the size. The enclosed cockpit is reassuring with small children aboard.",
        "Rig costs are cut in half with a glass-fibre flagpole as the mast base, profile-less furlers and a wishbone boom that keeps the sail low. The speed prediction gives 10 knots in force 4. Two 10 hp outboards replace a smelly, expensive inboard.",
      ],
      delivery: ["E-book with building instructions and 36 DXF drawings", "Study plan, 18 pages; refunded when you order the plans"],
      photos: [["KD1000Nside", "KD 1000, side view"], ["KD1000perNB", "Rendering"], ["KD1000_outside_use", "Hull built in Brazil"], ["KD1000-hullins_use", "Inside a hull"], ["KD1000bow_use", "Bow"], ["KD1000deck_use", "Deck"], ["KD100beam_use", "Beam"], ["KD1000ruhousing_use", "Rudder housing"], ["KD1000layout_web", "Layout"]],
      layout: "KD1000layout_web",
      videos: [],
      page: "https://ikarus342000.org/KD1000page.html",
    },
    {
      id: "kd-105", name: "KD 105", cat: "offshore", rig: "sail", year: null,
      tagline: "A fast, demountable 10.5 m catamaran you can still transport",
      loa: 10.5, beam: 6.34, weight: 1700, hours: null, hoursEst: 1500, estBasis: "Bernd gives no figure but calls it quick to build for its size. The KD 860 (1,800 kg) takes about 1,200 hours and the KD 1000 (2,000 kg) about 2,000.", plan: 970, study: 20, sleeps: "",
      spec: [["Length", "10.50 m, without rudders"], ["Beam", "6.34 m"], ["Beam, hull centres", "5.00 m"], ["Draught, hulls", "0.40 m"], ["Empty weight", "about 1,700 kg"], ["Loaded weight", "3,000 kg"], ["Main + jib", "37 + 17 m²"], ["Reacher", "48 m²"], ["Beams", "aluminium mast sections"], ["Windward", "daggerboards or anti-vortex panels"]],
      text: [
        "A demountable catamaran that is relatively easy to transport, and a fast one: spectacular sailing comes first. The nacelle is fairly big but still small enough to handle for transport.",
        "The trapezoid hulls are quick and easy to build, and the boat is quick to build for its size. The beams are aluminium mast sections, and you choose daggerboards or anti-vortex panels for windward work. One is under construction in Southampton, UK.",
      ],
      delivery: ["46 drawings, mostly DXF AutoCAD files", "Study plan with list of materials, dynamic stability diagram and speed prediction"],
      photos: [["DUO105webdef", "KD 105, rendering"], ["DUO105sloopweb_1", "Sloop rig"], ["Fairinghull", "Fairing a hull in Southampton"], ["Hullhalf", "Hull under construction"], ["Inside", "Inside a hull"], ["DUO105layoutbig", "Layout"]],
      layout: "DUO105layoutbig",
      videos: [],
      page: "https://ikarus342000.org/KD105page.html",
    },
    {
      id: "kd-122-voyager", name: "KD 122 Voyager", cat: "offshore", rig: "sail", year: null,
      tagline: "A 12 m go-anywhere boat for six, at the lowest possible cost",
      loa: 12.0, beam: 6.2, weight: 3100, hours: 2500, plan: 1980, study: 20, sleeps: "6",
      spec: [["Length", "12.00 m"], ["Waterline", "11.95 m"], ["Beam", "6.20 m"], ["Draught, rudders up / down", "0.6 / 0.8 m"], ["Empty weight", "3,100 kg"], ["Payload", "1,900 kg"], ["Sail area", "56 m² roller main, 69 m² battened"], ["Genoa", "53 m²"]],
      text: [
        "Light, fast, easy to build and cheap to keep. The asymmetric hulls follow the famous CSK designs, and the ends are kept light for an easy motion at sea. It has everything six people need for long journeys; the geodetic deckhouse gives 1.9 m headroom and the hulls 1.85 to 2.1 m.",
        "The A-frame mast is made from glass-fibre flagpoles or aluminium tubes, cutting the rig cost by about 70%, and it folds forward so you can raise and lower it yourself. With 60 cm draught you can anchor in small coves and skip expensive marinas.",
        "The plans have 45 CAD drawings, mostly 1:1, and a construction manual. Around 2,500 hours is realistic.",
      ],
      delivery: ["45 CAD drawings, mostly 1:1", "Construction manual", "Study plan, 18 pages with example drawing and list of materials"],
      photos: [["KD122port_web_1", "Voyager in port"], ["KD122_uengine_web", "Under way"], ["KD122artern_H260", "Stern"], ["KD122_inside_255", "Inside"], ["KD122_bathK_255", "Bathroom"], ["Hullturning", "Flipping a hull in one minute"], ["KD122pano_1000", "Building a Voyager"], ["KD122_engine_mount_225", "Engine mount"], ["KD122_pano_750", "Layout"], ["Splash_crob_200", "On the slipway"], ["KD122masttop_225", "A-frame mast top"]],
      layout: "KD122_pano_750",
      videos: [["Flipping a hull in real time", "https://www.youtube.com/watch?v=15dUCdxK0pc"], ["Launch", "https://www.youtube.com/watch?v=iuO8gdiswWk"]],
      page: "https://ikarus342000.org/VOYAGERpage.html",
    },
    {
      id: "manta", name: "MANTA", cat: "offshore", rig: "sail", year: 1988,
      tagline: "When the marina ends, MANTA begins",
      loa: 12.45, beam: 7.1, weight: 4800, hours: 3000, hoursText: "2,800–3,200 h", plan: null, study: 20, sleeps: "6+",
      spec: [["Length", "12.45 m"], ["Beam", "7.10 m"], ["Draught", "0.85 m"], ["Empty weight", "4,800 kg"], ["Loaded weight", "7,200 kg"], ["Main + jib + staysail", "42 + 28 + 18 m²"], ["Reacher", "80 m²"], ["Engines", "2 × 22 hp"]],
      text: [
        "A go-anywhere expedition catamaran drawn in 1988 around three priorities: strength, simplicity and seaworthiness. MANTAs have crossed the North Atlantic, worked as diving boats in the Mediterranean and carried guests in Asia. The first owner sailed the North Sea in winter and came home from the London Boat Show in force 9.",
        "Standing headroom is 2 m or more throughout. The galley is in the hull, near the centre of gravity, where the boat moves least. The space between the shower and the collision bulkhead can be a workshop; one owner kept a scooter there. Base speed is 10.2 knots, and 18 knots is not unusual.",
        "The hulls are built upside down, and a bulkhead set-up method works even on an uneven workshop floor, with no building stocks. Expect 2,800 to 3,200 hours.",
      ],
      delivery: ["Building instructions and all drawings as JPG", "Licence to build one boat for private use", "Study plan, 16 pages with list of materials and photo show"],
      photos: [["bv_img18", "MANTA under sail"], ["bv_img19", "Ushuaia, Patagonia"], ["bv_img20", "In the marina"], ["bv_img17", "In harbour at night"], ["Saloonstb_1240", "Saloon, starboard"], ["Saloonbb_1240", "Saloon, port"], ["Bathroom_color_450", "Bathroom"], ["Berthr2_450", "Berth"], ["bv_img21", "In the galley"], ["Underfloorengineroom_450", "Engine room with saildrive"], ["Bulkheadset_680", "Bulkheads set up"], ["Hullturned_680", "Hull turned"], ["Deckwork_680", "Deck work"], ["Layout2", "Layout"]],
      layout: "Layout2",
      videos: [],
      page: "https://ikarus342000.org/MANTApage.html",
    },
    {
      id: "skimmer-2", name: "Skimmer 2", cat: "experimental", rig: "power", year: null,
      tagline: "A two-seat wing-in-ground-effect craft, legally a boat",
      loa: null, beam: null, weight: 320, hours: null, plan: 180, study: null, sleeps: "",
      spec: [["Capacity", "2 persons, 230 kg"], ["Empty weight", "320 kg"], ["Flotation", "1,100 kg"], ["Engine", "105 hp, Alfa Romeo boxer or Subaru"], ["Lift fan", "electric drive, 8 kW motor"], ["Speed", "70 km/h hovering, 130 km/h cruise, 160 km/h max."], ["Cruising height", "0.6–1.5 m in ground effect"], ["Range, projected", "450 km"], ["Max. wave height", "1.0 m"]],
      text: [
        "The Skimmer 2 began as a joint project of Universal Hovercraft, K-designs and the Spanish government, to build a fast craft against drug smuggling from Morocco. A new government stopped the funding, but the prototype was already finished, so the work went on.",
        "It is designed as an IMO Type B wing-in-ground-effect craft, so it is legally a boat and needs no pilot licence. It can briefly jump to clear an obstacle but cannot fly without ground effect. It runs over snow, ice and water and can start from a ramp or a beach.",
        "Any handy person can build it from foam, plywood, epoxy and glass, but you must be able to read technical drawings. Materials cost around $4,000 plus the engine and propellers; the prototype was built in two months. The lift drive is now electric: an 8 kW motor, shown as schematics.",
      ],
      delivery: ["13 drawings as PDF files", "Schematics for the electric lift drive", "Eligibility to join the K-designs builders' forum"],
      photos: [["Skimfast_norge", "Skimmer 2 built in Norway, at speed"], ["Skimmer_mare_menor_speed", "Test run on the Mar Menor, Spain"], ["Skimfront_enh_505", "Front view"], ["Skim2_wing_enh_505", "Wing and duct"], ["Skim2_inside-enh_505", "Cockpit"], ["Skim2_motest_enh_505", "Engine test"], ["SkimmerconstrNORWAY_505", "The Norwegian build"], ["Skim2_constr2_505", "Hull construction"], ["Skim2_engine_505", "Engine installed"], ["Cabconfoam_enh_505", "Cabin in foam"], ["Formforduct_enh_505", "Mould for the duct"], ["Russian_modelskimmer2_344", "A model of the Skimmer 2"], ["Skim2sideblue", "Side view"], ["Skim_bulkhead", "Drawing: bulkhead"], ["Listofdrawings", "List of drawings"], ["Howivo", "Front view drawing"]],
      videos: [],
      page: "https://ikarus342000.org/Skimmer2.html",
    },
  ],
  // Bernd's articles, rewritten from his pages (sources in `pages`). Figures: [folder under img/, file, caption].
  articles: [
    {
      id: "biplane-rig", title: "The biplane (parallel) rig", pages: ["https://ikarus342000.org/Biplanrig.html", "https://ikarus342000.org/FAQ.html"],
      lede: "Two sails side by side: more sail area on shorter spars, a lower centre of effort and a faster boat, if the boat is light.",
      cover: ["articles/biplane-rig", "Parigdiagram"],
      sections: [
        { p: ["The DUO 425 was the first beach catamaran with a parallel rig. After some theoretical work Bernd tried it in 1984, when a windsurf rig cost about 80 German marks. The biggest advantage over a sloop (jib and main) is more sail area with a lower centre of effort, so the boat can carry sail in stronger wind, which means more power and more speed."],
          figs: [["articles/biplane-rig", "Parigdiagram", "Apparent wind at different boat speeds, true wind 10 knots from abeam"]] },
        { h: "How it works", p: ["In the drawing the true wind blows at 90° to the boat at 10 knots. As the boat speeds up, the apparent wind grows and moves forward, so the sails get more power. The lighter the boat, the higher its basic speed.",
            "The windward sail is set at a bigger angle than the leeward one. The same amount of air that enters the gap between the sails has to leave it, so the air speeds up in the narrowing gap: suction on the windward sail and push on the leeward sail both increase, and the total force grows.",
            "The limit is how far forward the apparent wind comes. Before the leading edge collapses, the angle of attack becomes too small for good lift. If the boat is too heavy for its sail area, the leeward sail is blanketed: then forget the parallel rig."] },
        { h: "Strong points", p: ["For the same area the sails sit on lower spars, so the centre of effort is lower: the boat is more stable and less likely to capsize. Each sail is smaller and easier to handle, and sleeves give the leading edge a better shape. The masts are usually free-standing: a simpler deck, less windage, less clutter and no rattling rigging at anchor. Reefing works the normal way or by rotating the masts.",
            "In strong wind the boat can be sailed as a Pacific proa, which increases the effective beam and stability by 50%, or as an Atlantic proa, Dick Newick's idea, with the sails to windward. With only one sail up, stability increases by 100%."],
          figs: [["articles/biplane-rig", "DUO425_recordb", "DUO 425 at Lelystad, the Netherlands: this boat reached 32 knots"], ["articles/biplane-rig", "Sass2_biplane_roller", "Resonance 80, an H.J. Sass design from 1983 with rotating masts"]] },
        { h: "How to sail it", p: ["The parallel rig only works when the boat sails to windward; off the wind the leeward sail is out of the air stream. On a light boat such as the DUO 425 or DUO 800, in force 3 to 5, even a beam reach brings the apparent wind forward.",
            "Set the leeward sail until it draws, then play with the windward sail, which works like a jib: the boat reaches its best speed when that sail's angle is slightly bigger. In force 4 this still works with the wind about 120° off the bow. Goose-winging costs about a third of the power, so tack downwind instead: the distance is longer but the higher speed gets you there sooner."],
          figs: [["articles/biplane-rig", "DUO480cab10", "DUO 480 in New Zealand"], ["articles/biplane-rig", "DUO800india3_small", "DUO 800 in India"], ["articles/biplane-rig", "Schionning_Radicale-Bay8000", "Radical Bay by Schionning"]] },
      ],
      videos: [["Yves Parlier's Hydraplaneur", "https://www.youtube.com/watch?v=AY0ssDA70gY"], ["DUO 480 in New Zealand", "https://www.youtube.com/watch?v=PiTbOKIuxlY"], ["Radical Bay by Schionning", "https://www.youtube.com/watch?v=Dq_wUxR0sdI"]],
      books: ["C.A. Marchaj, Aero-Hydrodynamics of Sailing", "Fabio Fossati, Aero-Hydrodynamics and the Performance of Sailing Yachts", "Joseph Norwood Jr., High Speed Sailing: Design Factors"],
      designs: ["duo-425", "duo-480-c", "duo-800", "kd-860-open"],
    },
    {
      id: "wig", title: "Wing-in-ground-effect craft", pages: ["https://ikarus342000.org/WIGINTRO.html", "https://ikarus342000.org/INTROUSE.html", "https://ikarus342000.org/INTRO2.html", "https://ikarus342000.org/Index.html"],
      lede: "Craft that skim just above the water on a cushion of ground effect: faster than any boat, far cheaper to run than an aircraft, and legally a boat.",
      cover: ["articles/wig", "Skimmernorway_use2"],
      sections: [
        { p: ["Interest in wing-in-ground-effect (WIG) craft is back. Many new designs are only concepts with the usual PR language; others exist as renderings or prototypes, but none is in full production yet. One exception is a two-seat electric tandem craft from China, about US $120,000, with 85 km/h top speed and about 80 km range. Or you can build a WIG craft yourself for around US $7,000.",
            "There is no better example of ground-effect flight than the albatross, which can fly over 1,000 km without flapping its wings. Bernd revived his WIG pages from 2005; they were for information only for a while, because such craft are hard to certify in most countries, and the Skimmer 2 plans are now available again."],
          figs: [["articles/wig", "Skimmernorway_use2", "Skimmer 2 built in Norway"], ["articles/wig", "Albatross_water2", "The albatross uses ground effect"]] },
        { h: "Why use WIG craft", p: ["WIG craft skim very low, typically at about 10% of their wingspan. At that height the drag almost disappears, and the pressure under the wing gives about 80% more lift than out of ground effect. Together this makes them extremely efficient: about half the fuel of an aircraft and only about 15% of a fast boat. A big WIG craft reaches about 210 mph, faster than any ship, and over medium distances it can match air travel door to door.",
            "They are not aircraft and can be certified as boats. The Skimmer 2 was provisionally certified as a boat; in the USA the Amphistar Xtreme Xplorer and Universal Hovercraft's UH 18 are classed as boats by the USCG, as are Mr. Jörg's tandem WIG in Germany, the Hoverwing in the Netherlands (provisionally) and the Volga 2 in Russia. So no aircraft engines or materials are needed, and a boat licence is enough; for professional use, check national rules."],
          figs: [["articles/wig", "IVolga_Vasy_1_enhBW", "Volga 2"]] },
        { h: "The three IMO classes", p: ["Type A craft cannot leave ground effect. Type B craft can jump to clear an obstacle by turning speed into height, but cannot fly for long without ground effect. Type C craft are in principle aircraft that can operate safely in ground effect, and must be certified as aircraft."] },
        { h: "In short", p: ["Economy: low fuel use, low maintenance, short payback. Cruising speed 120 to 400 km/h depending on size, no seasickness and no airsickness, easy to handle. Safety: the craft are self-stable, settle slowly onto the surface if the engine fails, and are unsinkable. Ecology: low emissions, closed-circuit or air-cooled engines, almost no wash, so no damage to riverbanks or the underwater world, and low noise."],
          figs: [["articles/wig", "Skimt", "Skimmer 2"]] },
      ],
      designs: ["skimmer-2"],
    },
    {
      id: "wig-types", title: "WIG craft: types and a short theory", pages: ["https://ikarus342000.org/INTRO3.html", "https://ikarus342000.org/THEORY.html", "https://ikarus342000.org/INTRO.html"],
      lede: "Why a wing near the surface lifts twice as much, and how reversed deltas, ekranoplans and tandems keep stable.",
      cover: ["articles/wig-types", "Ekranoplan_01"],
      sections: [
        { h: "A short theory", p: ["A wing in ground effect produces about twice the lift of a wing in free air, so a WIG craft the size of an aircraft can carry almost twice the payload. The pressure plots show the very high pressure under the wing near the ground and the much cleaner flow around it."],
          figs: [["articles/wig-types", "Wingl_01", "Wing in ground effect: high pressure below, clean flow"], ["articles/wig-types", "wiglift_01", "Wing in free flight. Green: suction on top; red: pressure below"]] },
        { h: "Longitudinal stability", p: ["The wing's centre of effort and the craft's centre of gravity must line up, as in any aircraft. But the centre of effort sits at about 25% of the chord in free flight and about 45% in ground effect. When a WIG craft climbs out of ground effect, the centre of effort moves forward and the nose wants to pitch up, so WIG craft need large horizontal stabilisers. The tandem WIG is not affected; the reversed delta (Professor Lippisch's designs) is less affected and needs only a small stabiliser; the square wing of the ekranoplans is affected most and needs a large one."] },
        { h: "Types of WIG craft", p: ["WIG craft are not aircraft, and the design rules differ. An aircraft rotates to about 14° for maximum lift at take-off; a WIG craft has to get airborne without that, and flying fast so close to the surface it must be self-stable. Several types were developed for that.",
            "Reversed delta (Lippisch principle): very stable in itself, so a small stabiliser is enough. Fischer Flugmechanik in Germany developed these; they can jump and use V-hulls like a speedboat. Most power is needed to get over the hull's hump speed; once flying, cruise needs about half. Examples are the Airfisch series and the Flightship FS 8.",
            "Ekranoplan: a Russian invention with very low aspect-ratio wings (1:4), endplates and flaps. At the start air is blown under the wings to form a cushion; at cruise the propellers tilt for more thrust. Big ones use separate engines for thrust and for blowing. They all have huge stabilisers and are also called PAR-WIG (power-augmented ram). The largest exceeded 500 tons."],
          figs: [["articles/wig-types", "Lipwig", "Reversed-delta WIG craft"], ["articles/wig-types", "Ekranoplan_01", "Ekranoplan"], ["articles/wig-types", "amphis", "Amphistar"], ["articles/wig-types", "tandem", "Tandem WIG"]] },
      ],
      links: [["K.V. Rozhdestvensky: aerodynamics of ground-effect craft (paper)", "https://www.sciencedirect.com/science/article/abs/pii/S0376042106000637"]],
      designs: ["skimmer-2"],
    },
    {
      id: "wig-hover", title: "Hover-WIG craft and a field for experimenters", pages: ["https://ikarus342000.org/HOWIG.html", "https://ikarus342000.org/ACTEC.html"],
      lede: "Combining a hovercraft cushion with a wing, and why ground effect is still open ground for home experimenters.",
      cover: ["articles/wig-hover", "Server"],
      sections: [
        { h: "Dynamic hovercraft", p: ["In hover mode a forward fan builds an air cushion that lifts the craft, so it also works on land, ice or snow. This needs less power to leave the water than a WIG craft with a V-hull. At about 43 knots the wings take over; once in ground effect the forward fan idles and takes no more power. With a splitter on the main propeller no separate lift propeller is needed, and that is the next step.",
            "Besides the pure WIG types there are other combinations, such as surface-effect ships combined with a WIG, the Hoverwing from Fischer Flugmechanik, and new hovercraft and ram-wing hybrids. The Skimmer 2 is one of them."],
          figs: [["articles/wig-hover", "HOWIGSYS", "Hover-WIG configuration"], ["articles/wig-hover", "HOWIHO", "Hover-WIG airflow"], ["articles/wig-hover", "SKIMMER2", "Skimmer 2"]] },
        { h: "A field for experimenters", p: ["Much theoretical work exists on ground effect and stability, but very few WIG craft. Meanwhile the race for speed has ignored the effect, sometimes with dramatic results: in 2001 two of Mercedes' three Le Mans cars flipped over backwards, and every year some high-speed racing catamarans flip.",
            "A Russian company built the SERVER, a dynamic hovercraft cruising at 120 km/h on only 54 hp, with the engine and propeller in front, pulling instead of pushing, a far more stable layout. A folding front skirt could let such a craft lift off on static pressure until it is fast enough for dynamic lift, then fold up for WIG mode; on water only, a catamaran configuration works well. Surface area, speed, cruising height, payload, cockpit size, stabilisation and ergonomics all have to be weighed.",
            "The Cushion Crow, a flying body-wing, is another original idea with promising experiments. A warning for model builders: because of how a wing behaves in ground effect, models only work on flat water or at a large scale; most models are really low-flying aircraft."],
          figs: [["articles/wig-hover", "Server", "SERVER dynamic hovercraft"], ["articles/wig-hover", "Servper", "SERVER"], ["articles/wig-hover", "CC1sttry5", "Cushion Crow, first try"]] },
      ],
      designs: ["skimmer-2"],
    },
  ],
  // Designs in the portfolio without their own page yet.
  more: ["KD 650 (plans US $190, study US $12)", "MAXI", "DUO 1000", "Houseboat 7.5 m"],
};
